### ISSUE TITLE
Game crash when tries to send data to server, when server is down

### ISSUE THREAD

**Issue by Arxcis** [EmilZach/Sentence-Crusher#12]
Dersom serveren ikke kjører, så prøver spillet å sende data til serveren likevel. Det gjør at spillet crasher til slutt. 

Her må vi få på plass en exception handler eller noe som skjekker om serveren er oppe å går før spillet forsøker å sende data.

**Comment by technocake** [comment]
try:
    ##send_something_to_server
except Exception as e:
  logger.debug("Error communicating with server -  %s" % e)
  handle_server_connection_error()

2016-03-25 18:15 GMT+01:00 Jonas notifications@github.com:

**Comment by raglew** [comment]
Thanks technocake. Implemented your suggestion with a slight modification.
