### ISSUE TITLE
Change the variable D to data. Capital letters not allowed in other than Classes

### ISSUE THREAD

**Issue by Arxcis** [EmilZach/Sentence-Crusher#13]

**Comment by EmilZach** [comment]
Should I change DB to database as well?

**Comment by Arxcis** [comment]
database, eller d_base, eller dbase, eller file, eller storage, eller
26. mar. 2016 10.04 p.m. skrev "Emil Teigland Zachariassen" <
notifications@github.com>:

**Comment by EmilZach** [comment]
Alright.

**Comment by EmilZach** [comment]
The files "db.py" and "Flask_server.py" has not been edited yet, so this issue will stay open.

**Comment by raglew** [comment]
Emil: To keep things neat & consistent, can you do the same with the two server files?

**Comment by EmilZach** [comment]
I don't think I can do it today, but I can of course do it tomorrow if you want me to. :-)

**Comment by raglew** [comment]
No worries. And thanks. Tomorrow is good. You've done a lot already today.

**Comment by EmilZach** [comment]
Thanks :-)

**Comment by EmilZach** [comment]
This issue has now been finished. Closing the issue now.
