### ISSUE TITLE
Restructure file system after class session 30.03.16 

### ISSUE THREAD

**Issue by Arxcis** [EmilZach/Sentence-Crusher#20]
Source/Game
Source/Shared
Source/Server
Docs/

**Comment by EmilZach** [comment]
The project structure is now complete. The only thing we have to do is to sort the classes in to the right folders. DataGuy and StorageGuy are going to the "Shared" folder, while GfxGuy, LogicGuy and InputGuy will stay in the "Game" folder. The "Server" folder will stay the same for now, but we will eventually take away s_data.py and s_storage.py when the "Shared" folder is complete.

Let me know if any changes should be made or you have a better idea, both to the project structure and the plan.

**Comment by Arxcis** [comment]
Jeg fyrer løs på norsk. Håper det er greit  :+1: 
Vi snakket i timen om at storage.py bare skulle brukes av serveren, for å gjøre hele programmet enklere. Derfor Skal det ikke være nødvendig å ha storage.py i "shared"-folder, og den bør forbli i "server"-folder.

**Comment by EmilZach** [comment]
Sånt skjer når jeg ikke får med meg alt, men flott at du nevnte det. :+1:  Jeg starter i allefall i morgen.

**Comment by Arxcis** [comment]
Jeg har tenkt litt på dette, og synes at å introdusere en shared-mappe faktisk gjør spillet litt mer komplisert enn det trenger å være. Samtidig som det vil gjøre det vanskeligere å flytte game-client bort fra serveren. Jeg ser ikke gevinsten med å gjøre dette i det hele tatt.

**Comment by raglew** [comment]
Helt enig :)

**Comment by EmilZach** [comment]
Jeg har prøvd i flere dager med å ordne slik at man kunne importere .py filer fra Shared-mappen, men ingenting har fungert for meg. Hvis vi ikke skal bruke Shared-mappen, så er det greit for meg.

**Comment by Arxcis** [comment]
OKi, case closed.
