### ISSUE TITLE
Get sorted highscore is in the wrong class - what is the right class?

### ISSUE THREAD

**Issue by Arxcis** [EmilZach/Sentence-Crusher#21]

**Comment by EmilZach** [comment]
Due to StorageGuy writing the highscore to a text file, I would say the function should go from DataGuy to StorageGuy.

**Comment by Arxcis** [comment]
It is already in StorageGuy..
31. mar. 2016 4.14 p.m. skrev "Emil Teigland Zachariassen" <
notifications@github.com>:

**Comment by EmilZach** [comment]
Not in s_data.py, I think...

**Comment by EmilZach** [comment]
I can't check that right now, so I am not completely sure.

**Comment by Arxcis** [comment]
I checked and completely sure ;)
31. mar. 2016 4.27 p.m. skrev "Emil Teigland Zachariassen" <
notifications@github.com>:

**Comment by Arxcis** [comment]
OK her er mitt forslag:

Til nå har DataGuy-klassen fungerte på følgende måte:

Attributter:
- Attributtene til DataGuy har inneholdt øyeblikksdata(ikke historiske
  data) som spillet er avhengig av for å fungere.

Metoder:
- Metodene til DataGuy har hatt som oppgave å hente inn data fra andre
  steder, for å lagre dem i sine attributter. F.eks hente inn time.clock()
  data.

Forslaget mitt er å utvide virkeområdet til DataGuy , til også å inkludere
metoder som går ut på å generere nye data, på grunnlag av data som allerede
er lagret i DataGuy. Dette gjelder funksjonen calc_points() i LogicGuy og
get_sorted_highscorelist() i StorageGuy.

Foreslår å endre navnet på disse to metodene til og plassere dem i DataGuy
;)
- generate_points()
- generate_sorted_highscorelist()

mvh Jonas

**Comment by Arxcis** [comment]
Har blitt enig med meg selv, og flyttet get_sorted_highscore() til DataGuy-klassen hvor den kan føle seg mer hjemme. Have a look guys.
