### ISSUE TITLE
Implement "flask.request" - "post" data to server, "get" data from server

### ISSUE THREAD

**Issue by Arxcis** [EmilZach/Sentence-Crusher#4]
When a program speaks with a web-application  - our game.py and our flask-web-server.py) - it does so with HTTP requests. 

There are two main HTTP request types - the HTTP GET method and HTTP POST method. 
GET is meant for fetching something from the server. 
A GET request implies that no side effects will happen when the server receives our request.
Side effects may be changing something in the database for instance.

To do that, we use the POST request. 
https://github.com/technocake/flask-eksempel/blob/master/httpclient.py 
# get_highscore_list()

In the flask webserver, the function  **get_highscore_list()**  should return the current list of higscores from the database.  It should return this in a format that is good for programs to read, not HTML, preferably text. (maybe JSON). This will be used by the game program to ask the server for the highscore-list and then show this data to the player.
# add_higscore(...)

The **add_highscore(...)** function in the webserver should accept post requests from the game program containing data for a new highscore. 
 [Jonas, can you fill in the details about the data in a game result / highscore? name, time, points. etc]

**Comment by technocake** [comment]
Here is example of retrieving POST requests in flask:
https://github.com/technocake/flask-eksempel/blob/master/webserver.py#L105-L130

**Comment by raglew** [comment]
I think this issue can be closed. Scores can now be posted to the server and stored, and a list of scores can be returned to the game client.

**Comment by Arxcis** [comment]
Fantastic work! :)
27. mar. 2016 8.51 p.m. skrev "raglew" notifications@github.com:

**Comment by raglew** [comment]
Thanks Robin. By the way, who is Kjell? Are you guys related? If so, greetings from me. Nice to have another man on board  :)

**Comment by raglew** [comment]
oops... thanks arxcis... jonas!

**Comment by Arxcis** [comment]
Kjell is just me, using my brothers computer, forgetting to change user-name
27. mar. 2016 9.22 p.m. skrev "raglew" notifications@github.com:

**Comment by raglew** [comment]
Too bad.. would be nice to have your brother on board. Can he program?

**Comment by Arxcis** [comment]
Trying to inspire him , but its difficult. He prefers to use games, not
make them..
27. mar. 2016 9.27 p.m. skrev "raglew" notifications@github.com:

**Comment by raglew** [comment]
Perhaps one day he will see the light :)
