### ISSUE TITLE
graphics.countdown_321() not showing correctly in some enviroments

### ISSUE THREAD

**Issue by Arxcis** [EmilZach/Sentence-Crusher#5]
Issue description: 
 I noen miljøeer som spillet blir kjørt i, så funker ikke animasjonen slik som den skal. Plutselig kommer alle 3 tallene på en gang, istedet for at hvert tall kommer hvert sekund.

**Comment by Arxcis** [comment]
This happens because time.sleep() dosen't work properly. I just figured out that this could be caused by the built in python buffering. If we somehow could turn off the buffering.

**Comment by Arxcis** [comment]
http://stackoverflow.com/questions/107705/disable-output-buffering

Here is an explanation

**Comment by technocake** [comment]
The code relevant for this issue is here: https://github.com/EmilZach/Sentence-Crusher/blob/master/Game/graphics.py#L45-L52

**Comment by EmilZach** [comment]
I need someone to test the program in other environments. I don't run Linux or Mac, so I can't check if it works.

**Comment by Arxcis** [comment]
Its not just different operating systems , but also if you run in GIT-bash
or cmd or inside PyCharms
27. mar. 2016 10.28 p.m. skrev "Emil Teigland Zachariassen" <
notifications@github.com>:

**Comment by EmilZach** [comment]
Oh, so you meant terminal environments. I can test on Bash since I don't use PyCharm.

**Comment by EmilZach** [comment]
Can confirm it works with cmd and Bash. I'll mark it as closed unless the issue persists.
