### ISSUE TITLE
Pass user_name to new_game() using parameter

### ISSUE THREAD

**Issue by Arxcis** [EmilZach/Sentence-Crusher#8]

**Comment by Arxcis** [comment]
This issue is not relevant anymore after switch to object-oriented data handling.

**Comment by raglew** [comment]
Have to reopen this issue. User name isn't being registered when same user restarts a new game.

**Comment by Arxcis** [comment]
Ill look into it
27. mar. 2016 8.57 p.m. skrev "raglew" notifications@github.com:

**Comment by Arxcis** [comment]
The reason is here -->>
https://github.com/EmilZach/Sentence-Crusher/blob/master/Game/main.py#L29-L35

User name is stored before the While-loop. After each while -loop all data
gets reset. Even the name is deleted from DataGuy()
27. mar. 2016 9.13 p.m. skrev "JoJo" jonas.solsvik@gmail.com:

**Comment by Arxcis** [comment]
*from data-object
27. mar. 2016 9.38 p.m. skrev "JoJo" jonas.solsvik@gmail.com:

**Comment by Arxcis** [comment]
After each while-loop we have to reset all data except player name.

**Comment by raglew** [comment]
How do you get that link to main.py with the particluar section marked out? That's cool.

**Comment by raglew** [comment]
What about: if continue_game == Y then store D.user in a variable: do the game data reset, and then set D.user = variable.

**Comment by Arxcis** [comment]
Yes thats a solution. But another solution is go into DataGuy() -class, and
maybe make a reset-method. Which only resets the data we want to reset,
leaving the rest of the data untouched.
27. mar. 2016 10.01 p.m. skrev "raglew" notifications@github.com:

**Comment by raglew** [comment]
That would be an even better solution: instead of D.**init**() in line 64 of main.py, call a reset method that is basically the same as def **init**(self) in the DataGuy class, but modified not to change D.user.

**Comment by Arxcis** [comment]
Yes , excactly. We reset-method can hold data that changes every new-game.
And the init-method can hold data that sticks around.
27. mar. 2016 10.16 p.m. skrev "raglew" notifications@github.com:

**Comment by raglew** [comment]
Who wants to implement?

**Comment by EmilZach** [comment]
Doesn't matter for me. I can fix the issue if people wants to

**Comment by raglew** [comment]
Thanks Emil :)

**Comment by EmilZach** [comment]
No problem :-)

**Comment by EmilZach** [comment]
Is this what you wanted? Let me know if I should change anything.

**Comment by Arxcis** [comment]
Its works perfect. I changed it a bit more though, since you don't have to define all those variables TWICE in DataGuy(). Once is more than enough ;)
