### ISSUE TITLE
Stylesheet not rendered by flask

### ISSUE THREAD

**Issue by raglew** [EmilZach/Sentence-Crusher#9]

**Comment by Arxcis** [comment]
Oh no! !

**Comment by raglew** [comment]
Vel vel.. it's only color..
No. Just kidding dude. I'm on to it.

**Comment by raglew** [comment]
Issue resolved. Stylesheet placed in a folder called static -- ref. flask tutorial @ http://flask.pocoo.org/docs/0.10/tutorial/css/#tutorial-css

**Comment by Arxcis** [comment]
Well done! :+1:
